version: '3.4'
services:

  eth1_node:
    image: ethereum/client-go:stable
    entrypoint: []
    command: sh /scripts/start-eth1.sh
    volumes:
      - ./eth1_data:/root/.ethereum
      - ./scripts:/scripts
    ports:
      # Map the p2p port(30303)
      - 30303:30303/tcp
      - 30303:30303/udp
    env_file: .env

  teku_node:
    build:
        context: teku_docker
    entrypoint: []
    command: sh /scripts/start-teku.sh
    volumes:
      - ./teku_data:/teku_data
      - ./scripts:/scripts
      - ./keys:/keys
    ports:
      # Map the p2p port(9000) and REST API port(5051)
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5051:5051/tcp
    env_file: .env
